// Code generated by protoc-gen-go. DO NOT EDIT.
// source: approval.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApprovalResult int32

const (
	ApprovalResult_UNKNOWN  ApprovalResult = 0
	ApprovalResult_APPROVED ApprovalResult = 1
	ApprovalResult_REJECTED ApprovalResult = 2
)

var ApprovalResult_name = map[int32]string{
	0: "UNKNOWN",
	1: "APPROVED",
	2: "REJECTED",
}
var ApprovalResult_value = map[string]int32{
	"UNKNOWN":  0,
	"APPROVED": 1,
	"REJECTED": 2,
}

func (x ApprovalResult) String() string {
	return proto.EnumName(ApprovalResult_name, int32(x))
}
func (ApprovalResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_approval_cf05cc9ecd3ad5e1, []int{0}
}

type Approval struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	User                 *User                `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Batch                string               `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Result               ApprovalResult       `protobuf:"varint,5,opt,name=result,proto3,enum=pb.ApprovalResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Approval) Reset()         { *m = Approval{} }
func (m *Approval) String() string { return proto.CompactTextString(m) }
func (*Approval) ProtoMessage()    {}
func (*Approval) Descriptor() ([]byte, []int) {
	return fileDescriptor_approval_cf05cc9ecd3ad5e1, []int{0}
}
func (m *Approval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approval.Unmarshal(m, b)
}
func (m *Approval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approval.Marshal(b, m, deterministic)
}
func (dst *Approval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approval.Merge(dst, src)
}
func (m *Approval) XXX_Size() int {
	return xxx_messageInfo_Approval.Size(m)
}
func (m *Approval) XXX_DiscardUnknown() {
	xxx_messageInfo_Approval.DiscardUnknown(m)
}

var xxx_messageInfo_Approval proto.InternalMessageInfo

func (m *Approval) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Approval) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Approval) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Approval) GetBatch() string {
	if m != nil {
		return m.Batch
	}
	return ""
}

func (m *Approval) GetResult() ApprovalResult {
	if m != nil {
		return m.Result
	}
	return ApprovalResult_UNKNOWN
}

func init() {
	proto.RegisterType((*Approval)(nil), "pb.Approval")
	proto.RegisterEnum("pb.ApprovalResult", ApprovalResult_name, ApprovalResult_value)
}

func init() { proto.RegisterFile("approval.proto", fileDescriptor_approval_cf05cc9ecd3ad5e1) }

var fileDescriptor_approval_cf05cc9ecd3ad5e1 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x31, 0x6b, 0xf3, 0x30,
	0x10, 0x86, 0x3f, 0xe9, 0x73, 0x52, 0xf7, 0x52, 0x8c, 0x39, 0x3a, 0x08, 0x53, 0xa8, 0xe9, 0x64,
	0x32, 0x28, 0x90, 0x4e, 0x1d, 0x43, 0xe3, 0xa5, 0x05, 0x27, 0x88, 0xa4, 0x9d, 0xa5, 0x5a, 0x4d,
	0x0d, 0x0e, 0x12, 0xb2, 0xdc, 0x1f, 0xd5, 0x5f, 0x59, 0x2c, 0xc7, 0x43, 0x37, 0xdd, 0xbd, 0x8f,
	0x9e, 0x7b, 0x21, 0x91, 0xd6, 0x3a, 0xf3, 0x2d, 0x5b, 0x6e, 0x9d, 0xf1, 0x06, 0xa9, 0x55, 0xd9,
	0xfd, 0xc9, 0x98, 0x53, 0xab, 0x57, 0x61, 0xa3, 0xfa, 0xcf, 0x95, 0x6f, 0xce, 0xba, 0xf3, 0xf2,
	0x6c, 0x47, 0x28, 0x83, 0xbe, 0xd3, 0x6e, 0x7c, 0x3f, 0xfc, 0x10, 0x88, 0x37, 0x17, 0x07, 0x26,
	0x40, 0x9b, 0x9a, 0x91, 0x9c, 0x14, 0xd7, 0x82, 0x36, 0x35, 0x72, 0x88, 0x6a, 0xe9, 0x35, 0xa3,
	0x39, 0x29, 0x16, 0xeb, 0x8c, 0x8f, 0x62, 0x3e, 0x89, 0xf9, 0x61, 0x12, 0x8b, 0xc0, 0xe1, 0x1d,
	0x44, 0x83, 0x9a, 0xfd, 0x0f, 0x7c, 0xcc, 0xad, 0xe2, 0xc7, 0x4e, 0x3b, 0x11, 0xb6, 0x78, 0x0b,
	0x33, 0x25, 0xfd, 0xc7, 0x17, 0x8b, 0xc2, 0x81, 0x71, 0xc0, 0x25, 0xcc, 0x9d, 0xee, 0xfa, 0xd6,
	0xb3, 0x59, 0x4e, 0x8a, 0x64, 0x8d, 0xc3, 0xaf, 0xa9, 0x91, 0x08, 0x89, 0xb8, 0x10, 0xcb, 0x27,
	0x48, 0xfe, 0x26, 0xb8, 0x80, 0xab, 0x63, 0xf5, 0x5a, 0xed, 0xde, 0xab, 0xf4, 0x1f, 0xde, 0x40,
	0xbc, 0xd9, 0xef, 0xc5, 0xee, 0xad, 0xdc, 0xa6, 0x64, 0x98, 0x44, 0xf9, 0x52, 0x3e, 0x1f, 0xca,
	0x6d, 0x4a, 0xd5, 0x3c, 0x94, 0x7e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xad, 0x8a, 0xc4, 0x1e,
	0x31, 0x01, 0x00, 0x00,
}
