// Code generated by protoc-gen-go. DO NOT EDIT.
// source: approval.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Approval struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	User                 *User                `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Batch                *LabBatch            `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Result               string               `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Approval) Reset()         { *m = Approval{} }
func (m *Approval) String() string { return proto.CompactTextString(m) }
func (*Approval) ProtoMessage()    {}
func (*Approval) Descriptor() ([]byte, []int) {
	return fileDescriptor_approval_7868aca2b8057f81, []int{0}
}
func (m *Approval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approval.Unmarshal(m, b)
}
func (m *Approval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approval.Marshal(b, m, deterministic)
}
func (dst *Approval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approval.Merge(dst, src)
}
func (m *Approval) XXX_Size() int {
	return xxx_messageInfo_Approval.Size(m)
}
func (m *Approval) XXX_DiscardUnknown() {
	xxx_messageInfo_Approval.DiscardUnknown(m)
}

var xxx_messageInfo_Approval proto.InternalMessageInfo

func (m *Approval) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Approval) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Approval) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Approval) GetBatch() *LabBatch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func (m *Approval) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Approval)(nil), "pb.Approval")
}

func init() { proto.RegisterFile("approval.proto", fileDescriptor_approval_7868aca2b8057f81) }

var fileDescriptor_approval_7868aca2b8057f81 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x41, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0x49, 0x6c, 0x4b, 0x1d, 0xa5, 0x42, 0x16, 0x12, 0x8a, 0x60, 0xe9, 0xaa, 0x1b, 0x53,
	0xd0, 0x13, 0xe8, 0xda, 0x55, 0xd0, 0x03, 0x24, 0x36, 0xd6, 0x42, 0x4a, 0x42, 0x92, 0x7a, 0xa2,
	0x77, 0xd0, 0x47, 0x27, 0xed, 0x6e, 0xe6, 0xfb, 0x7f, 0xe6, 0x1b, 0x68, 0x94, 0xf7, 0xc1, 0xfd,
	0x2b, 0x2b, 0x7c, 0x70, 0xc9, 0x31, 0xea, 0x75, 0xfb, 0x3c, 0x3b, 0x37, 0x5b, 0x33, 0x22, 0xd1,
	0xdb, 0xef, 0x98, 0x96, 0xd5, 0xc4, 0xa4, 0x56, 0x9f, 0x4b, 0x2d, 0x6c, 0xd1, 0x84, 0x63, 0x7e,
	0xb0, 0x4a, 0xbf, 0x68, 0x95, 0x7e, 0xfe, 0x32, 0xe8, 0x2f, 0x04, 0xea, 0xf7, 0xe3, 0x28, 0x6b,
	0x80, 0x2e, 0x13, 0x27, 0x1d, 0x19, 0x6e, 0x25, 0x5d, 0x26, 0x26, 0xa0, 0x98, 0x54, 0x32, 0x9c,
	0x76, 0x64, 0xb8, 0x7b, 0x6d, 0x45, 0x36, 0x89, 0xd3, 0x24, 0xbe, 0x4e, 0x93, 0xc4, 0x1e, 0x7b,
	0x82, 0x62, 0x77, 0xf1, 0x1b, 0xec, 0xd7, 0xc2, 0x6b, 0xf1, 0x1d, 0x4d, 0x90, 0x48, 0x59, 0x0f,
	0x25, 0x9a, 0x79, 0x81, 0xf1, 0xfd, 0x1e, 0x7f, 0x2a, 0xfd, 0xb1, 0x33, 0x99, 0x23, 0xf6, 0x08,
	0x55, 0x30, 0x71, 0xb3, 0x89, 0x97, 0xf8, 0xc5, 0xb1, 0xe9, 0x0a, 0x9d, 0x6f, 0xd7, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xad, 0xcf, 0x55, 0x39, 0x01, 0x01, 0x00, 0x00,
}
