// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Catalog struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date1                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date1,proto3" json:"date1,omitempty"`
	Date2                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date2,proto3" json:"date2,omitempty"`
	Date3                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date3,proto3" json:"date3,omitempty"`
	Date4                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date4,proto3" json:"date4,omitempty"`
	String1              string               `protobuf:"bytes,6,opt,name=string1,proto3" json:"string1,omitempty"`
	String2              string               `protobuf:"bytes,7,opt,name=string2,proto3" json:"string2,omitempty"`
	String3              string               `protobuf:"bytes,8,opt,name=string3,proto3" json:"string3,omitempty"`
	String4              string               `protobuf:"bytes,9,opt,name=string4,proto3" json:"string4,omitempty"`
	Number1              float64              `protobuf:"fixed64,10,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              float64              `protobuf:"fixed64,11,opt,name=number2,proto3" json:"number2,omitempty"`
	Number3              float64              `protobuf:"fixed64,12,opt,name=number3,proto3" json:"number3,omitempty"`
	Number4              float64              `protobuf:"fixed64,13,opt,name=number4,proto3" json:"number4,omitempty"`
	Int1                 int64                `protobuf:"varint,14,opt,name=int1,proto3" json:"int1,omitempty"`
	Int2                 int64                `protobuf:"varint,15,opt,name=int2,proto3" json:"int2,omitempty"`
	Int3                 int64                `protobuf:"varint,16,opt,name=int3,proto3" json:"int3,omitempty"`
	Int4                 int64                `protobuf:"varint,17,opt,name=int4,proto3" json:"int4,omitempty"`
	Bool1                bool                 `protobuf:"varint,18,opt,name=bool1,proto3" json:"bool1,omitempty"`
	Bool2                bool                 `protobuf:"varint,19,opt,name=bool2,proto3" json:"bool2,omitempty"`
	Bool3                bool                 `protobuf:"varint,20,opt,name=bool3,proto3" json:"bool3,omitempty"`
	Bool4                bool                 `protobuf:"varint,21,opt,name=bool4,proto3" json:"bool4,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Catalog) Reset()         { *m = Catalog{} }
func (m *Catalog) String() string { return proto.CompactTextString(m) }
func (*Catalog) ProtoMessage()    {}
func (*Catalog) Descriptor() ([]byte, []int) {
	return fileDescriptor_catalog_0e783dbc52d3029a, []int{0}
}
func (m *Catalog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Catalog.Unmarshal(m, b)
}
func (m *Catalog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Catalog.Marshal(b, m, deterministic)
}
func (dst *Catalog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Catalog.Merge(dst, src)
}
func (m *Catalog) XXX_Size() int {
	return xxx_messageInfo_Catalog.Size(m)
}
func (m *Catalog) XXX_DiscardUnknown() {
	xxx_messageInfo_Catalog.DiscardUnknown(m)
}

var xxx_messageInfo_Catalog proto.InternalMessageInfo

func (m *Catalog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Catalog) GetDate1() *timestamp.Timestamp {
	if m != nil {
		return m.Date1
	}
	return nil
}

func (m *Catalog) GetDate2() *timestamp.Timestamp {
	if m != nil {
		return m.Date2
	}
	return nil
}

func (m *Catalog) GetDate3() *timestamp.Timestamp {
	if m != nil {
		return m.Date3
	}
	return nil
}

func (m *Catalog) GetDate4() *timestamp.Timestamp {
	if m != nil {
		return m.Date4
	}
	return nil
}

func (m *Catalog) GetString1() string {
	if m != nil {
		return m.String1
	}
	return ""
}

func (m *Catalog) GetString2() string {
	if m != nil {
		return m.String2
	}
	return ""
}

func (m *Catalog) GetString3() string {
	if m != nil {
		return m.String3
	}
	return ""
}

func (m *Catalog) GetString4() string {
	if m != nil {
		return m.String4
	}
	return ""
}

func (m *Catalog) GetNumber1() float64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *Catalog) GetNumber2() float64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

func (m *Catalog) GetNumber3() float64 {
	if m != nil {
		return m.Number3
	}
	return 0
}

func (m *Catalog) GetNumber4() float64 {
	if m != nil {
		return m.Number4
	}
	return 0
}

func (m *Catalog) GetInt1() int64 {
	if m != nil {
		return m.Int1
	}
	return 0
}

func (m *Catalog) GetInt2() int64 {
	if m != nil {
		return m.Int2
	}
	return 0
}

func (m *Catalog) GetInt3() int64 {
	if m != nil {
		return m.Int3
	}
	return 0
}

func (m *Catalog) GetInt4() int64 {
	if m != nil {
		return m.Int4
	}
	return 0
}

func (m *Catalog) GetBool1() bool {
	if m != nil {
		return m.Bool1
	}
	return false
}

func (m *Catalog) GetBool2() bool {
	if m != nil {
		return m.Bool2
	}
	return false
}

func (m *Catalog) GetBool3() bool {
	if m != nil {
		return m.Bool3
	}
	return false
}

func (m *Catalog) GetBool4() bool {
	if m != nil {
		return m.Bool4
	}
	return false
}

func init() {
	proto.RegisterType((*Catalog)(nil), "pb.Catalog")
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor_catalog_0e783dbc52d3029a) }

var fileDescriptor_catalog_0e783dbc52d3029a = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x6e, 0xb3, 0x30,
	0x10, 0x46, 0x65, 0x12, 0x42, 0xe2, 0xfc, 0xc9, 0xdf, 0xba, 0xa9, 0xf4, 0x29, 0x9b, 0xa2, 0xae,
	0x58, 0x91, 0x62, 0xfb, 0x06, 0xbd, 0x01, 0xea, 0x05, 0xa0, 0x50, 0x84, 0x04, 0x18, 0x11, 0xe7,
	0xb0, 0xbd, 0x4d, 0x25, 0xc0, 0xd8, 0x4b, 0x76, 0xcc, 0x7b, 0xf3, 0x06, 0x21, 0xe8, 0xe9, 0x3b,
	0xd3, 0x59, 0xa3, 0xaa, 0xb8, 0x1f, 0x94, 0x56, 0xcc, 0xeb, 0xf3, 0xeb, 0x5b, 0xa5, 0x54, 0xd5,
	0x94, 0xb7, 0x91, 0xe4, 0x8f, 0x9f, 0x9b, 0xae, 0xdb, 0xf2, 0xae, 0xb3, 0xb6, 0x9f, 0x96, 0xde,
	0x7f, 0xb7, 0x34, 0xf8, 0x9c, 0x32, 0x76, 0xa6, 0x5e, 0x5d, 0x80, 0x84, 0x24, 0x3a, 0xa4, 0x5e,
	0x5d, 0xb0, 0x0f, 0xea, 0x17, 0x99, 0x2e, 0x13, 0x78, 0x21, 0x89, 0x8e, 0xfc, 0x1a, 0x4f, 0xc7,
	0x62, 0x73, 0x2c, 0xfe, 0x32, 0xc7, 0xd2, 0x69, 0xd1, 0x14, 0x1c, 0x9b, 0x75, 0x05, 0x37, 0x85,
	0xc0, 0x76, 0x5d, 0x21, 0x4c, 0x21, 0xe1, 0xaf, 0x2b, 0x24, 0x03, 0x0d, 0xee, 0x7a, 0xa8, 0xbb,
	0x2a, 0xc1, 0x6e, 0xfc, 0x38, 0x33, 0x5a, 0xc3, 0x11, 0xb8, 0x86, 0x5b, 0x23, 0xb0, 0x77, 0x8d,
	0xb0, 0x46, 0xe2, 0xe0, 0x9a, 0xf1, 0x3d, 0xdd, 0xa3, 0xcd, 0xcb, 0x21, 0x01, 0x0d, 0x49, 0x44,
	0x52, 0x33, 0x5a, 0xc3, 0x71, 0x74, 0x0d, 0xb7, 0x46, 0xe0, 0x9f, 0x6b, 0x84, 0x35, 0x12, 0x27,
	0xd7, 0x48, 0xc6, 0xe8, 0xb6, 0xee, 0x74, 0x82, 0x73, 0x48, 0xa2, 0x4d, 0x3a, 0x3e, 0xcf, 0x8c,
	0xe3, 0xff, 0xc2, 0xf8, 0xcc, 0x04, 0x9e, 0x16, 0x26, 0x66, 0x26, 0xf1, 0xbc, 0x30, 0xc9, 0x2e,
	0xd4, 0xcf, 0x95, 0x6a, 0x12, 0xb0, 0x90, 0x44, 0xfb, 0x74, 0x1a, 0x0c, 0xe5, 0x78, 0xb1, 0x94,
	0x1b, 0x2a, 0x70, 0xb1, 0x54, 0x18, 0x2a, 0xf1, 0x6a, 0xa9, 0xcc, 0x77, 0xe3, 0x2f, 0x11, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0x17, 0xc6, 0xe3, 0x98, 0x02, 0x00, 0x00,
}
