// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comm-dash-service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommDashParams struct {
	Suppliers            []string `protobuf:"bytes,1,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommDashParams) Reset()         { *m = CommDashParams{} }
func (m *CommDashParams) String() string { return proto.CompactTextString(m) }
func (*CommDashParams) ProtoMessage()    {}
func (*CommDashParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_comm_dash_service_91c181fdef4e1057, []int{0}
}
func (m *CommDashParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommDashParams.Unmarshal(m, b)
}
func (m *CommDashParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommDashParams.Marshal(b, m, deterministic)
}
func (dst *CommDashParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommDashParams.Merge(dst, src)
}
func (m *CommDashParams) XXX_Size() int {
	return xxx_messageInfo_CommDashParams.Size(m)
}
func (m *CommDashParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CommDashParams.DiscardUnknown(m)
}

var xxx_messageInfo_CommDashParams proto.InternalMessageInfo

func (m *CommDashParams) GetSuppliers() []string {
	if m != nil {
		return m.Suppliers
	}
	return nil
}

type GridCommDashRequest struct {
	Grid                 *GridInput      `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	Params               *CommDashParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GridCommDashRequest) Reset()         { *m = GridCommDashRequest{} }
func (m *GridCommDashRequest) String() string { return proto.CompactTextString(m) }
func (*GridCommDashRequest) ProtoMessage()    {}
func (*GridCommDashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_comm_dash_service_91c181fdef4e1057, []int{1}
}
func (m *GridCommDashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridCommDashRequest.Unmarshal(m, b)
}
func (m *GridCommDashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridCommDashRequest.Marshal(b, m, deterministic)
}
func (dst *GridCommDashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridCommDashRequest.Merge(dst, src)
}
func (m *GridCommDashRequest) XXX_Size() int {
	return xxx_messageInfo_GridCommDashRequest.Size(m)
}
func (m *GridCommDashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GridCommDashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GridCommDashRequest proto.InternalMessageInfo

func (m *GridCommDashRequest) GetGrid() *GridInput {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *GridCommDashRequest) GetParams() *CommDashParams {
	if m != nil {
		return m.Params
	}
	return nil
}

type GridCommDash struct {
	Grid                 *GridOutput `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	Rows                 []*CommDash `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GridCommDash) Reset()         { *m = GridCommDash{} }
func (m *GridCommDash) String() string { return proto.CompactTextString(m) }
func (*GridCommDash) ProtoMessage()    {}
func (*GridCommDash) Descriptor() ([]byte, []int) {
	return fileDescriptor_comm_dash_service_91c181fdef4e1057, []int{2}
}
func (m *GridCommDash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridCommDash.Unmarshal(m, b)
}
func (m *GridCommDash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridCommDash.Marshal(b, m, deterministic)
}
func (dst *GridCommDash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridCommDash.Merge(dst, src)
}
func (m *GridCommDash) XXX_Size() int {
	return xxx_messageInfo_GridCommDash.Size(m)
}
func (m *GridCommDash) XXX_DiscardUnknown() {
	xxx_messageInfo_GridCommDash.DiscardUnknown(m)
}

var xxx_messageInfo_GridCommDash proto.InternalMessageInfo

func (m *GridCommDash) GetGrid() *GridOutput {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *GridCommDash) GetRows() []*CommDash {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*CommDashParams)(nil), "pb.CommDashParams")
	proto.RegisterType((*GridCommDashRequest)(nil), "pb.GridCommDashRequest")
	proto.RegisterType((*GridCommDash)(nil), "pb.GridCommDash")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommDashServiceClient is the client API for CommDashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommDashServiceClient interface {
	Create(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error)
	StartProgress(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error)
	StopProgress(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error)
	Cancel(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error)
	Close(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error)
	Grid(ctx context.Context, in *GridCommDashRequest, opts ...grpc.CallOption) (*GridCommDash, error)
}

type commDashServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommDashServiceClient(cc *grpc.ClientConn) CommDashServiceClient {
	return &commDashServiceClient{cc}
}

func (c *commDashServiceClient) Create(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commDashServiceClient) Update(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commDashServiceClient) Remove(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commDashServiceClient) StartProgress(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/StartProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commDashServiceClient) StopProgress(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/StopProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commDashServiceClient) Cancel(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commDashServiceClient) Close(ctx context.Context, in *CommDash, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commDashServiceClient) Grid(ctx context.Context, in *GridCommDashRequest, opts ...grpc.CallOption) (*GridCommDash, error) {
	out := new(GridCommDash)
	err := c.cc.Invoke(ctx, "/pb.CommDashService/Grid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommDashServiceServer is the server API for CommDashService service.
type CommDashServiceServer interface {
	Create(context.Context, *CommDash) (*Response, error)
	Update(context.Context, *CommDash) (*Response, error)
	Remove(context.Context, *CommDash) (*Response, error)
	StartProgress(context.Context, *CommDash) (*Response, error)
	StopProgress(context.Context, *CommDash) (*Response, error)
	Cancel(context.Context, *CommDash) (*Response, error)
	Close(context.Context, *CommDash) (*Response, error)
	Grid(context.Context, *GridCommDashRequest) (*GridCommDash, error)
}

func RegisterCommDashServiceServer(s *grpc.Server, srv CommDashServiceServer) {
	s.RegisterService(&_CommDashService_serviceDesc, srv)
}

func _CommDashService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommDash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).Create(ctx, req.(*CommDash))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommDashService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommDash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).Update(ctx, req.(*CommDash))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommDashService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommDash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).Remove(ctx, req.(*CommDash))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommDashService_StartProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommDash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).StartProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/StartProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).StartProgress(ctx, req.(*CommDash))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommDashService_StopProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommDash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).StopProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/StopProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).StopProgress(ctx, req.(*CommDash))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommDashService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommDash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).Cancel(ctx, req.(*CommDash))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommDashService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommDash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).Close(ctx, req.(*CommDash))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommDashService_Grid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridCommDashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommDashServiceServer).Grid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CommDashService/Grid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommDashServiceServer).Grid(ctx, req.(*GridCommDashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommDashService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CommDashService",
	HandlerType: (*CommDashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CommDashService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CommDashService_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _CommDashService_Remove_Handler,
		},
		{
			MethodName: "StartProgress",
			Handler:    _CommDashService_StartProgress_Handler,
		},
		{
			MethodName: "StopProgress",
			Handler:    _CommDashService_StopProgress_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _CommDashService_Cancel_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _CommDashService_Close_Handler,
		},
		{
			MethodName: "Grid",
			Handler:    _CommDashService_Grid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comm-dash-service.proto",
}

func init() {
	proto.RegisterFile("comm-dash-service.proto", fileDescriptor_comm_dash_service_91c181fdef4e1057)
}

var fileDescriptor_comm_dash_service_91c181fdef4e1057 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x6e, 0xc2, 0x30,
	0x10, 0x85, 0xf9, 0x2b, 0x12, 0xc3, 0x5f, 0xe5, 0x2e, 0x40, 0x51, 0x17, 0x34, 0x52, 0x2b, 0x54,
	0x95, 0x2c, 0xe0, 0x08, 0x54, 0xaa, 0xba, 0x2a, 0x32, 0xed, 0x01, 0x0c, 0xb1, 0x20, 0x12, 0xc6,
	0xee, 0x8c, 0x43, 0xef, 0xdc, 0x53, 0x54, 0x36, 0x49, 0x21, 0x6c, 0xc2, 0x2e, 0x99, 0xf7, 0xcd,
	0x7b, 0xc9, 0xb3, 0x61, 0xb0, 0xd6, 0x4a, 0x4d, 0x62, 0x41, 0xdb, 0x09, 0x49, 0x3c, 0x24, 0x6b,
	0x19, 0x19, 0xd4, 0x56, 0xb3, 0x9a, 0x59, 0x05, 0xfd, 0x7f, 0xf1, 0x38, 0x0c, 0x60, 0x83, 0x49,
	0x9c, 0x3d, 0xf7, 0x50, 0x92, 0xd1, 0x7b, 0xca, 0x16, 0xc2, 0x08, 0x7a, 0x73, 0xad, 0xd4, 0xab,
	0xa0, 0xed, 0x42, 0xa0, 0x50, 0xc4, 0xee, 0xa1, 0x45, 0xa9, 0x31, 0xbb, 0x44, 0x22, 0x0d, 0xab,
	0xa3, 0xfa, 0xb8, 0xc5, 0x4f, 0x83, 0x30, 0x86, 0xbb, 0x37, 0x4c, 0xe2, 0x7c, 0x87, 0xcb, 0xef,
	0x54, 0x92, 0x65, 0x0f, 0xd0, 0x70, 0x21, 0xc3, 0xea, 0xa8, 0x3a, 0x6e, 0x4f, 0xbb, 0x91, 0x59,
	0x45, 0x0e, 0x7b, 0xdf, 0x9b, 0xd4, 0x72, 0x2f, 0xb1, 0x67, 0x68, 0x1a, 0x9f, 0x30, 0xac, 0x79,
	0x88, 0x39, 0xa8, 0x98, 0xcd, 0x33, 0x22, 0xfc, 0x84, 0xce, 0x79, 0x0a, 0x0b, 0x0b, 0xf6, 0xbd,
	0xdc, 0xfe, 0x23, 0xb5, 0x27, 0xff, 0x11, 0x34, 0x50, 0xff, 0x38, 0xf7, 0xfa, 0xb8, 0x3d, 0xed,
	0x9c, 0xbb, 0x73, 0xaf, 0x4c, 0x7f, 0x6b, 0xd0, 0xcf, 0x47, 0xcb, 0x63, 0x6d, 0xec, 0x09, 0x9a,
	0x73, 0x94, 0xc2, 0x4a, 0x56, 0xd8, 0x08, 0xfc, 0x1b, 0xcf, 0xba, 0x0a, 0x2b, 0x8e, 0xfb, 0x32,
	0xf1, 0x55, 0x1c, 0x97, 0x4a, 0x1f, 0xca, 0xb8, 0x09, 0x74, 0x97, 0x56, 0xa0, 0x5d, 0xa0, 0xde,
	0xa0, 0x24, 0x2a, 0xc1, 0x5f, 0xa0, 0xb3, 0xb4, 0xda, 0x5c, 0x49, 0xbb, 0x9f, 0x12, 0xfb, 0xb5,
	0xdc, 0x95, 0x70, 0x8f, 0x70, 0x33, 0xdf, 0x69, 0x2a, 0xfb, 0xd6, 0x19, 0x34, 0x5c, 0xdb, 0x6c,
	0x90, 0xf7, 0x7e, 0x71, 0xfa, 0xc1, 0xed, 0xa5, 0x10, 0x56, 0x56, 0x4d, 0x7f, 0xbf, 0x66, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xf5, 0xb9, 0x2a, 0xab, 0x02, 0x00, 0x00,
}
