// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grid.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GridRequest struct {
	PageNumber           int32    `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Query                string   `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	SortDirection        string   `protobuf:"bytes,4,opt,name=sortDirection,proto3" json:"sortDirection,omitempty"`
	SortField            string   `protobuf:"bytes,5,opt,name=sortField,proto3" json:"sortField,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GridRequest) Reset()         { *m = GridRequest{} }
func (m *GridRequest) String() string { return proto.CompactTextString(m) }
func (*GridRequest) ProtoMessage()    {}
func (*GridRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grid_7fc820741b8c6cf8, []int{0}
}
func (m *GridRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridRequest.Unmarshal(m, b)
}
func (m *GridRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridRequest.Marshal(b, m, deterministic)
}
func (dst *GridRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridRequest.Merge(dst, src)
}
func (m *GridRequest) XXX_Size() int {
	return xxx_messageInfo_GridRequest.Size(m)
}
func (m *GridRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GridRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GridRequest proto.InternalMessageInfo

func (m *GridRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *GridRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GridRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *GridRequest) GetSortDirection() string {
	if m != nil {
		return m.SortDirection
	}
	return ""
}

func (m *GridRequest) GetSortField() string {
	if m != nil {
		return m.SortField
	}
	return ""
}

type GridResponse struct {
	PageNumber           int32      `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int32      `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalCount           int32      `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Rows                 []*any.Any `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GridResponse) Reset()         { *m = GridResponse{} }
func (m *GridResponse) String() string { return proto.CompactTextString(m) }
func (*GridResponse) ProtoMessage()    {}
func (*GridResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grid_7fc820741b8c6cf8, []int{1}
}
func (m *GridResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridResponse.Unmarshal(m, b)
}
func (m *GridResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridResponse.Marshal(b, m, deterministic)
}
func (dst *GridResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridResponse.Merge(dst, src)
}
func (m *GridResponse) XXX_Size() int {
	return xxx_messageInfo_GridResponse.Size(m)
}
func (m *GridResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GridResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GridResponse proto.InternalMessageInfo

func (m *GridResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *GridResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GridResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GridResponse) GetRows() []*any.Any {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*GridRequest)(nil), "pb.GridRequest")
	proto.RegisterType((*GridResponse)(nil), "pb.GridResponse")
}

func init() { proto.RegisterFile("grid.proto", fileDescriptor_grid_7fc820741b8c6cf8) }

var fileDescriptor_grid_7fc820741b8c6cf8 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0xd0, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x60, 0xb6, 0x4d, 0xc4, 0x4e, 0xf5, 0xb2, 0xf4, 0xb0, 0x16, 0x29, 0xa1, 0x78, 0xc8,
	0x29, 0x05, 0x7d, 0x02, 0x51, 0xf4, 0xe6, 0x61, 0x7d, 0x82, 0xc4, 0x8c, 0x61, 0x21, 0xee, 0xa4,
	0xb3, 0xbb, 0x48, 0x7c, 0x0e, 0xdf, 0xc0, 0x17, 0x95, 0xee, 0xa2, 0xc6, 0x73, 0x8f, 0xff, 0xf7,
	0xcf, 0xe1, 0x67, 0x00, 0x3a, 0x36, 0x6d, 0x35, 0x30, 0x79, 0x92, 0xb3, 0xa1, 0x59, 0x5f, 0x74,
	0x44, 0x5d, 0x8f, 0xbb, 0x28, 0x4d, 0x78, 0xdd, 0xd5, 0x76, 0x4c, 0xf5, 0xf6, 0x4b, 0xc0, 0xf2,
	0x91, 0x4d, 0xab, 0x71, 0x1f, 0xd0, 0x79, 0xb9, 0x01, 0x18, 0xea, 0x0e, 0x9f, 0xc2, 0x5b, 0x83,
	0xac, 0x44, 0x21, 0xca, 0x5c, 0x4f, 0x44, 0xae, 0xe1, 0xf4, 0x90, 0x9e, 0xcd, 0x07, 0xaa, 0x59,
	0x6c, 0x7f, 0xb3, 0x5c, 0x41, 0xbe, 0x0f, 0xc8, 0xa3, 0x9a, 0x17, 0xa2, 0x5c, 0xe8, 0x14, 0xe4,
	0x15, 0x9c, 0x3b, 0x62, 0x7f, 0x6f, 0x18, 0x5f, 0xbc, 0x21, 0xab, 0xb2, 0xd8, 0xfe, 0x47, 0x79,
	0x09, 0x8b, 0x03, 0x3c, 0x18, 0xec, 0x5b, 0x95, 0xc7, 0x8b, 0x3f, 0xd8, 0x7e, 0x0a, 0x38, 0x4b,
	0x2b, 0xdd, 0x40, 0xd6, 0xe1, 0x51, 0x33, 0x37, 0x00, 0x9e, 0x7c, 0xdd, 0xdf, 0x51, 0xb0, 0x3e,
	0x6e, 0xcd, 0xf5, 0x44, 0x64, 0x09, 0x19, 0xd3, 0xbb, 0x53, 0x59, 0x31, 0x2f, 0x97, 0xd7, 0xab,
	0x2a, 0x3d, 0xaf, 0xfa, 0x79, 0x5e, 0x75, 0x6b, 0x47, 0x1d, 0x2f, 0x9a, 0x93, 0x68, 0x37, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0xfa, 0x04, 0xa8, 0x70, 0x01, 0x00, 0x00,
}
