// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab-material.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LabMaterial struct {
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// double stock = 3;
	Name                 string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LastSupplier         *Supplier `protobuf:"bytes,5,opt,name=lastSupplier,proto3" json:"lastSupplier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LabMaterial) Reset()         { *m = LabMaterial{} }
func (m *LabMaterial) String() string { return proto.CompactTextString(m) }
func (*LabMaterial) ProtoMessage()    {}
func (*LabMaterial) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_material_4c4f9f21acb931ca, []int{0}
}
func (m *LabMaterial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabMaterial.Unmarshal(m, b)
}
func (m *LabMaterial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabMaterial.Marshal(b, m, deterministic)
}
func (dst *LabMaterial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabMaterial.Merge(dst, src)
}
func (m *LabMaterial) XXX_Size() int {
	return xxx_messageInfo_LabMaterial.Size(m)
}
func (m *LabMaterial) XXX_DiscardUnknown() {
	xxx_messageInfo_LabMaterial.DiscardUnknown(m)
}

var xxx_messageInfo_LabMaterial proto.InternalMessageInfo

func (m *LabMaterial) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LabMaterial) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LabMaterial) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LabMaterial) GetLastSupplier() *Supplier {
	if m != nil {
		return m.LastSupplier
	}
	return nil
}

func init() {
	proto.RegisterType((*LabMaterial)(nil), "pb.LabMaterial")
}

func init() { proto.RegisterFile("lab-material.proto", fileDescriptor_lab_material_4c4f9f21acb931ca) }

var fileDescriptor_lab_material_4c4f9f21acb931ca = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcd, 0x41, 0xce, 0x82, 0x30,
	0x10, 0x05, 0xe0, 0xd0, 0xf0, 0xff, 0x89, 0x85, 0xb0, 0xe8, 0xaa, 0x61, 0x23, 0x71, 0xc5, 0x46,
	0x30, 0x7a, 0x0d, 0xdd, 0xe0, 0x09, 0x66, 0x64, 0x24, 0x4d, 0x5a, 0x3b, 0x81, 0x12, 0xaf, 0x6f,
	0x28, 0xb8, 0x70, 0xf7, 0xe6, 0xcb, 0xcb, 0x1b, 0xa9, 0x2c, 0xe0, 0xd1, 0x41, 0xa0, 0xd1, 0x80,
	0x6d, 0x78, 0xf4, 0xc1, 0x2b, 0xc1, 0x58, 0xee, 0x07, 0xef, 0x07, 0x4b, 0x6d, 0x14, 0x9c, 0x9f,
	0x6d, 0x30, 0x8e, 0xa6, 0x00, 0x8e, 0xd7, 0x52, 0x59, 0x4c, 0x33, 0xb3, 0x35, 0x34, 0xae, 0xf7,
	0xe1, 0x2d, 0xb3, 0x2b, 0xe0, 0x6d, 0x5b, 0x52, 0x85, 0x14, 0xa6, 0xd7, 0x49, 0x95, 0xd4, 0xbb,
	0x4e, 0x98, 0x5e, 0x29, 0x99, 0x3e, 0x7c, 0x4f, 0x5a, 0x44, 0x89, 0x79, 0xb1, 0x17, 0x38, 0xd2,
	0xe9, 0x6a, 0x4b, 0x56, 0x27, 0x99, 0x5b, 0x98, 0xc2, 0x7d, 0x1b, 0xd7, 0x7f, 0x55, 0x52, 0x67,
	0xe7, 0xbc, 0x61, 0x6c, 0xbe, 0xd6, 0xfd, 0x34, 0xf0, 0x3f, 0xfe, 0xbf, 0x7c, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x16, 0x73, 0x8f, 0x65, 0xca, 0x00, 0x00, 0x00,
}
