// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab-batch.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LabBatch struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location             *Location            `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Batch                string               `protobuf:"bytes,3,opt,name=Batch,proto3" json:"Batch,omitempty"`
	SupplierBatch        string               `protobuf:"bytes,4,opt,name=SupplierBatch,proto3" json:"SupplierBatch,omitempty"`
	Stock                float64              `protobuf:"fixed64,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=expires,proto3" json:"expires,omitempty"`
	Reanalysis           float64              `protobuf:"fixed64,8,opt,name=reanalysis,proto3" json:"reanalysis,omitempty"`
	Supplier             *Supplier            `protobuf:"bytes,9,opt,name=supplier,proto3" json:"supplier,omitempty"`
	Health               int32                `protobuf:"varint,10,opt,name=health,proto3" json:"health,omitempty"`
	Inflamability        int32                `protobuf:"varint,11,opt,name=inflamability,proto3" json:"inflamability,omitempty"`
	Reactivity           int32                `protobuf:"varint,12,opt,name=reactivity,proto3" json:"reactivity,omitempty"`
	LabMaterial          *LabMaterial         `protobuf:"bytes,13,opt,name=labMaterial,proto3" json:"labMaterial,omitempty"`
	Manufactured         *timestamp.Timestamp `protobuf:"bytes,14,opt,name=manufactured,proto3" json:"manufactured,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LabBatch) Reset()         { *m = LabBatch{} }
func (m *LabBatch) String() string { return proto.CompactTextString(m) }
func (*LabBatch) ProtoMessage()    {}
func (*LabBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_batch_fdaa14ef62f5c7dc, []int{0}
}
func (m *LabBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabBatch.Unmarshal(m, b)
}
func (m *LabBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabBatch.Marshal(b, m, deterministic)
}
func (dst *LabBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabBatch.Merge(dst, src)
}
func (m *LabBatch) XXX_Size() int {
	return xxx_messageInfo_LabBatch.Size(m)
}
func (m *LabBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_LabBatch.DiscardUnknown(m)
}

var xxx_messageInfo_LabBatch proto.InternalMessageInfo

func (m *LabBatch) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LabBatch) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LabBatch) GetBatch() string {
	if m != nil {
		return m.Batch
	}
	return ""
}

func (m *LabBatch) GetSupplierBatch() string {
	if m != nil {
		return m.SupplierBatch
	}
	return ""
}

func (m *LabBatch) GetStock() float64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *LabBatch) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *LabBatch) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *LabBatch) GetReanalysis() float64 {
	if m != nil {
		return m.Reanalysis
	}
	return 0
}

func (m *LabBatch) GetSupplier() *Supplier {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *LabBatch) GetHealth() int32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *LabBatch) GetInflamability() int32 {
	if m != nil {
		return m.Inflamability
	}
	return 0
}

func (m *LabBatch) GetReactivity() int32 {
	if m != nil {
		return m.Reactivity
	}
	return 0
}

func (m *LabBatch) GetLabMaterial() *LabMaterial {
	if m != nil {
		return m.LabMaterial
	}
	return nil
}

func (m *LabBatch) GetManufactured() *timestamp.Timestamp {
	if m != nil {
		return m.Manufactured
	}
	return nil
}

func init() {
	proto.RegisterType((*LabBatch)(nil), "pb.LabBatch")
}

func init() { proto.RegisterFile("lab-batch.proto", fileDescriptor_lab_batch_fdaa14ef62f5c7dc) }

var fileDescriptor_lab_batch_fdaa14ef62f5c7dc = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc9, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x42, 0xd7, 0xe9, 0x26, 0x59, 0x08, 0x59, 0x3d, 0x40, 0x84, 0x38, 0xe4, 0x42, 0x2a,
	0x96, 0x33, 0x07, 0xce, 0xe5, 0x62, 0xf8, 0x81, 0x71, 0xe2, 0xb6, 0x16, 0x4e, 0x6c, 0x25, 0x0e,
	0xa2, 0x5f, 0xc2, 0xef, 0xa2, 0x38, 0x71, 0x97, 0x53, 0x8f, 0x6f, 0xf3, 0xcc, 0x3c, 0xc3, 0x42,
	0x21, 0x7f, 0xe4, 0x68, 0xd3, 0x5d, 0x62, 0x4a, 0x6d, 0x35, 0x09, 0x0d, 0x5f, 0xde, 0x6d, 0xb5,
	0xde, 0x2a, 0xb1, 0x72, 0x0c, 0xaf, 0x37, 0x2b, 0x2b, 0x73, 0x51, 0x59, 0xcc, 0x4d, 0x6b, 0x5a,
	0x92, 0x26, 0x95, 0xa3, 0x15, 0xa5, 0x44, 0xd5, 0x71, 0x73, 0xa5, 0x53, 0xb4, 0x52, 0x17, 0x1e,
	0x57, 0xb5, 0x31, 0x4a, 0x8a, 0xb2, 0xc5, 0xf7, 0x7f, 0x3d, 0x18, 0xad, 0x91, 0xbf, 0x37, 0xb3,
	0xc8, 0x1c, 0x42, 0x99, 0xd1, 0x20, 0x0a, 0xe2, 0x31, 0x0b, 0x65, 0x46, 0x62, 0x18, 0xf9, 0x38,
	0x0d, 0xa3, 0x20, 0x9e, 0x3c, 0x4f, 0x13, 0xc3, 0x93, 0x75, 0xc7, 0xb1, 0x83, 0x4a, 0xae, 0xa1,
	0xef, 0x9e, 0xa0, 0x57, 0x2e, 0xdc, 0x02, 0xf2, 0x00, 0xb3, 0xcf, 0x6e, 0x5c, 0xab, 0xf6, 0x9c,
	0x7a, 0x4e, 0x36, 0xd9, 0xca, 0xea, 0xf4, 0x9b, 0xf6, 0xa3, 0x20, 0x0e, 0x58, 0x0b, 0x48, 0x02,
	0xbd, 0x0c, 0xad, 0xa0, 0x03, 0x37, 0x77, 0x99, 0xb4, 0xc7, 0x27, 0xfe, 0xf8, 0xe4, 0xcb, 0x1f,
	0xcf, 0x9c, 0x8f, 0xbc, 0xc2, 0x50, 0xfc, 0x1a, 0x59, 0x8a, 0x8a, 0x0e, 0x2f, 0x46, 0xbc, 0x95,
	0xdc, 0x02, 0x94, 0x02, 0x0b, 0x54, 0xfb, 0x4a, 0x56, 0x74, 0xe4, 0x16, 0x38, 0x61, 0x9a, 0x06,
	0x7c, 0x61, 0x74, 0x7c, 0x6c, 0xc0, 0x1f, 0xc0, 0x0e, 0x2a, 0xb9, 0x81, 0xc1, 0x4e, 0xa0, 0xb2,
	0x3b, 0x0a, 0x51, 0x10, 0xf7, 0x59, 0x87, 0x9a, 0x0e, 0x64, 0xb1, 0x51, 0x98, 0x23, 0x97, 0x4a,
	0xda, 0x3d, 0x9d, 0x38, 0xf9, 0x9c, 0xec, 0xf6, 0x48, 0xad, 0xfc, 0x69, 0x2c, 0x53, 0x67, 0x39,
	0x61, 0xc8, 0x13, 0x4c, 0x14, 0xf2, 0x8f, 0xee, 0x6f, 0xe9, 0xcc, 0xad, 0xb2, 0x70, 0x9f, 0x71,
	0xa4, 0xd9, 0xa9, 0x87, 0xbc, 0xc1, 0x34, 0xc7, 0xa2, 0xde, 0x60, 0x6a, 0xeb, 0x52, 0x64, 0x74,
	0x7e, 0xb1, 0x95, 0x33, 0x3f, 0x1f, 0x38, 0xc7, 0xcb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48,
	0xa7, 0xdb, 0x46, 0x8c, 0x02, 0x00, 0x00,
}
