// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab-material.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LabMaterial struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Stock                float64   `protobuf:"fixed64,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Name                 string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LastSupplier         *Supplier `protobuf:"bytes,5,opt,name=lastSupplier,proto3" json:"lastSupplier,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LabMaterial) Reset()         { *m = LabMaterial{} }
func (m *LabMaterial) String() string { return proto.CompactTextString(m) }
func (*LabMaterial) ProtoMessage()    {}
func (*LabMaterial) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_material_ce2ad1f4b5a7604a, []int{0}
}
func (m *LabMaterial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabMaterial.Unmarshal(m, b)
}
func (m *LabMaterial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabMaterial.Marshal(b, m, deterministic)
}
func (dst *LabMaterial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabMaterial.Merge(dst, src)
}
func (m *LabMaterial) XXX_Size() int {
	return xxx_messageInfo_LabMaterial.Size(m)
}
func (m *LabMaterial) XXX_DiscardUnknown() {
	xxx_messageInfo_LabMaterial.DiscardUnknown(m)
}

var xxx_messageInfo_LabMaterial proto.InternalMessageInfo

func (m *LabMaterial) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LabMaterial) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *LabMaterial) GetStock() float64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *LabMaterial) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LabMaterial) GetLastSupplier() *Supplier {
	if m != nil {
		return m.LastSupplier
	}
	return nil
}

func init() {
	proto.RegisterType((*LabMaterial)(nil), "pb.LabMaterial")
}

func init() { proto.RegisterFile("lab-material.proto", fileDescriptor_lab_material_ce2ad1f4b5a7604a) }

var fileDescriptor_lab_material_ce2ad1f4b5a7604a = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0xb1, 0x0e, 0x82, 0x30,
	0x14, 0x45, 0xd3, 0x0a, 0x26, 0x16, 0xc2, 0xd0, 0x38, 0x34, 0x2c, 0x12, 0x27, 0x16, 0xc1, 0xe8,
	0x6f, 0xe8, 0x82, 0x5f, 0xf0, 0x0a, 0x95, 0x34, 0xb6, 0xb6, 0xa1, 0xe5, 0x33, 0xfc, 0x67, 0x43,
	0x8b, 0x83, 0xdb, 0xbd, 0x27, 0x27, 0xef, 0x5d, 0x42, 0x15, 0xf0, 0x93, 0x06, 0x2f, 0x26, 0x09,
	0xaa, 0xb1, 0x93, 0xf1, 0x86, 0x62, 0xcb, 0xcb, 0xc3, 0x68, 0xcc, 0xa8, 0x44, 0x1b, 0x08, 0x9f,
	0x9f, 0xad, 0x97, 0x5a, 0x38, 0x0f, 0xda, 0x46, 0xa9, 0x2c, 0xdc, 0x6c, 0xad, 0x92, 0x62, 0x8a,
	0xfd, 0xf8, 0x41, 0x24, 0xbb, 0x01, 0xbf, 0xaf, 0xa7, 0x68, 0x41, 0xb0, 0x1c, 0x18, 0xaa, 0x50,
	0xbd, 0xeb, 0xb0, 0x1c, 0x28, 0x25, 0x49, 0x6f, 0x06, 0xc1, 0x70, 0x20, 0x21, 0xd3, 0x3d, 0x49,
	0x9d, 0x37, 0xfd, 0x8b, 0x6d, 0x2a, 0x54, 0xa3, 0x2e, 0x96, 0xc5, 0x7c, 0x83, 0x16, 0x2c, 0x89,
	0xe6, 0x92, 0xe9, 0x99, 0xe4, 0x0a, 0x9c, 0x7f, 0xac, 0x3f, 0x59, 0x5a, 0xa1, 0x3a, 0xbb, 0xe4,
	0x8d, 0xe5, 0xcd, 0x8f, 0x75, 0x7f, 0x06, 0xdf, 0x86, 0x59, 0xd7, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x61, 0x6a, 0xc8, 0xf1, 0xe1, 0x00, 0x00, 0x00,
}
