// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab-material-service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListLabMaterial struct {
	Materials            []*LabMaterial `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListLabMaterial) Reset()         { *m = ListLabMaterial{} }
func (m *ListLabMaterial) String() string { return proto.CompactTextString(m) }
func (*ListLabMaterial) ProtoMessage()    {}
func (*ListLabMaterial) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_material_service_4114806fc1ec9fbd, []int{0}
}
func (m *ListLabMaterial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLabMaterial.Unmarshal(m, b)
}
func (m *ListLabMaterial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLabMaterial.Marshal(b, m, deterministic)
}
func (dst *ListLabMaterial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLabMaterial.Merge(dst, src)
}
func (m *ListLabMaterial) XXX_Size() int {
	return xxx_messageInfo_ListLabMaterial.Size(m)
}
func (m *ListLabMaterial) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLabMaterial.DiscardUnknown(m)
}

var xxx_messageInfo_ListLabMaterial proto.InternalMessageInfo

func (m *ListLabMaterial) GetMaterials() []*LabMaterial {
	if m != nil {
		return m.Materials
	}
	return nil
}

type GridMaterialRequest struct {
	Grid                 *GridInput `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GridMaterialRequest) Reset()         { *m = GridMaterialRequest{} }
func (m *GridMaterialRequest) String() string { return proto.CompactTextString(m) }
func (*GridMaterialRequest) ProtoMessage()    {}
func (*GridMaterialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_material_service_4114806fc1ec9fbd, []int{1}
}
func (m *GridMaterialRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridMaterialRequest.Unmarshal(m, b)
}
func (m *GridMaterialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridMaterialRequest.Marshal(b, m, deterministic)
}
func (dst *GridMaterialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridMaterialRequest.Merge(dst, src)
}
func (m *GridMaterialRequest) XXX_Size() int {
	return xxx_messageInfo_GridMaterialRequest.Size(m)
}
func (m *GridMaterialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GridMaterialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GridMaterialRequest proto.InternalMessageInfo

func (m *GridMaterialRequest) GetGrid() *GridInput {
	if m != nil {
		return m.Grid
	}
	return nil
}

type GridMaterial struct {
	Grid                 *GridOutput    `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	Rows                 []*LabMaterial `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GridMaterial) Reset()         { *m = GridMaterial{} }
func (m *GridMaterial) String() string { return proto.CompactTextString(m) }
func (*GridMaterial) ProtoMessage()    {}
func (*GridMaterial) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_material_service_4114806fc1ec9fbd, []int{2}
}
func (m *GridMaterial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridMaterial.Unmarshal(m, b)
}
func (m *GridMaterial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridMaterial.Marshal(b, m, deterministic)
}
func (dst *GridMaterial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridMaterial.Merge(dst, src)
}
func (m *GridMaterial) XXX_Size() int {
	return xxx_messageInfo_GridMaterial.Size(m)
}
func (m *GridMaterial) XXX_DiscardUnknown() {
	xxx_messageInfo_GridMaterial.DiscardUnknown(m)
}

var xxx_messageInfo_GridMaterial proto.InternalMessageInfo

func (m *GridMaterial) GetGrid() *GridOutput {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *GridMaterial) GetRows() []*LabMaterial {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*ListLabMaterial)(nil), "pb.ListLabMaterial")
	proto.RegisterType((*GridMaterialRequest)(nil), "pb.GridMaterialRequest")
	proto.RegisterType((*GridMaterial)(nil), "pb.GridMaterial")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LabMaterialServiceClient is the client API for LabMaterialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LabMaterialServiceClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Load(ctx context.Context, in *Request, opts ...grpc.CallOption) (*LabMaterial, error)
	Create(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*ListLabMaterial, error)
	Validate(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error)
	Grid(ctx context.Context, in *GridMaterialRequest, opts ...grpc.CallOption) (*GridMaterial, error)
}

type labMaterialServiceClient struct {
	cc *grpc.ClientConn
}

func NewLabMaterialServiceClient(cc *grpc.ClientConn) LabMaterialServiceClient {
	return &labMaterialServiceClient{cc}
}

func (c *labMaterialServiceClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labMaterialServiceClient) Load(ctx context.Context, in *Request, opts ...grpc.CallOption) (*LabMaterial, error) {
	out := new(LabMaterial)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labMaterialServiceClient) Create(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labMaterialServiceClient) Update(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labMaterialServiceClient) Remove(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labMaterialServiceClient) List(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*ListLabMaterial, error) {
	out := new(ListLabMaterial)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labMaterialServiceClient) Validate(ctx context.Context, in *LabMaterial, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labMaterialServiceClient) Grid(ctx context.Context, in *GridMaterialRequest, opts ...grpc.CallOption) (*GridMaterial, error) {
	out := new(GridMaterial)
	err := c.cc.Invoke(ctx, "/pb.LabMaterialService/Grid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabMaterialServiceServer is the server API for LabMaterialService service.
type LabMaterialServiceServer interface {
	Ping(context.Context, *Request) (*Response, error)
	Load(context.Context, *Request) (*LabMaterial, error)
	Create(context.Context, *LabMaterial) (*Response, error)
	Update(context.Context, *LabMaterial) (*Response, error)
	Remove(context.Context, *LabMaterial) (*Response, error)
	List(context.Context, *LabMaterial) (*ListLabMaterial, error)
	Validate(context.Context, *LabMaterial) (*Response, error)
	Grid(context.Context, *GridMaterialRequest) (*GridMaterial, error)
}

func RegisterLabMaterialServiceServer(s *grpc.Server, srv LabMaterialServiceServer) {
	s.RegisterService(&_LabMaterialService_serviceDesc, srv)
}

func _LabMaterialService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabMaterialService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).Load(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabMaterialService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabMaterial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).Create(ctx, req.(*LabMaterial))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabMaterialService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabMaterial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).Update(ctx, req.(*LabMaterial))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabMaterialService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabMaterial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).Remove(ctx, req.(*LabMaterial))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabMaterialService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabMaterial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).List(ctx, req.(*LabMaterial))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabMaterialService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabMaterial)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).Validate(ctx, req.(*LabMaterial))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabMaterialService_Grid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabMaterialServiceServer).Grid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabMaterialService/Grid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabMaterialServiceServer).Grid(ctx, req.(*GridMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LabMaterialService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LabMaterialService",
	HandlerType: (*LabMaterialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LabMaterialService_Ping_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _LabMaterialService_Load_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LabMaterialService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _LabMaterialService_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _LabMaterialService_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _LabMaterialService_List_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _LabMaterialService_Validate_Handler,
		},
		{
			MethodName: "Grid",
			Handler:    _LabMaterialService_Grid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lab-material-service.proto",
}

func init() {
	proto.RegisterFile("lab-material-service.proto", fileDescriptor_lab_material_service_4114806fc1ec9fbd)
}

var fileDescriptor_lab_material_service_4114806fc1ec9fbd = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xde, 0xd6, 0xa5, 0xe8, 0xf4, 0x4f, 0xa6, 0x07, 0x4b, 0x4e, 0x35, 0x82, 0xb4, 0x48, 0xf7,
	0xd0, 0x5e, 0x3c, 0x0a, 0x1e, 0x44, 0xa8, 0x28, 0x15, 0xf5, 0x9c, 0x75, 0x43, 0x09, 0xb4, 0x4d,
	0x4c, 0xd2, 0xfa, 0xe2, 0x3e, 0x80, 0x64, 0xb3, 0x5b, 0x77, 0xb7, 0x1e, 0xf6, 0x96, 0x99, 0xef,
	0x67, 0x86, 0xf9, 0x02, 0x64, 0xcd, 0xe2, 0xe9, 0x86, 0x59, 0xae, 0x05, 0x5b, 0x4f, 0x0d, 0xd7,
	0x7b, 0xf1, 0xc9, 0x23, 0xa5, 0xa5, 0x95, 0xd8, 0x54, 0x31, 0xc1, 0x22, 0xee, 0xfb, 0xa4, 0xab,
	0xf9, 0xd7, 0x8e, 0x1b, 0x9b, 0x95, 0x3d, 0xcd, 0x8d, 0x92, 0x5b, 0x93, 0xc9, 0x08, 0xac, 0xb4,
	0x48, 0xfc, 0x9b, 0xde, 0x41, 0x7f, 0x21, 0x8c, 0x5d, 0xb0, 0xf8, 0x29, 0xf3, 0xc0, 0x29, 0x9c,
	0xe5, 0x7e, 0x66, 0xd8, 0x18, 0x9d, 0x8c, 0xdb, 0xb3, 0x7e, 0xa4, 0xe2, 0xa8, 0xc0, 0x59, 0xfe,
	0x31, 0xe8, 0x2d, 0x0c, 0x1e, 0xb4, 0x48, 0x0e, 0x90, 0x1f, 0x8d, 0x97, 0x10, 0xba, 0x31, 0xc3,
	0xc6, 0xa8, 0x31, 0x6e, 0xcf, 0xba, 0xce, 0xc0, 0xd1, 0x1e, 0xb7, 0x6a, 0x67, 0x97, 0x29, 0x44,
	0x3f, 0xa0, 0x53, 0x54, 0x22, 0x2d, 0x49, 0x7a, 0xb9, 0xe4, 0x79, 0x67, 0x0f, 0x1a, 0xbc, 0x82,
	0x50, 0xcb, 0x6f, 0x33, 0x6c, 0xfe, 0xbf, 0x57, 0x0a, 0xce, 0x7e, 0x9a, 0x80, 0x85, 0xee, 0xab,
	0x3f, 0x9a, 0xd3, 0xbe, 0x88, 0xed, 0x0a, 0xdb, 0x4e, 0x95, 0xed, 0x49, 0x3a, 0xbe, 0xf0, 0x07,
	0xa2, 0x01, 0x5e, 0x43, 0xb8, 0x90, 0x2c, 0x29, 0x93, 0xaa, 0x73, 0x68, 0x80, 0x13, 0x68, 0xdd,
	0x6b, 0xce, 0x2c, 0xc7, 0x2a, 0x78, 0x64, 0x39, 0x81, 0xd6, 0x9b, 0x4a, 0xea, 0x52, 0x97, 0x7c,
	0x23, 0xf7, 0x35, 0xa8, 0x11, 0x84, 0x2e, 0xb9, 0x63, 0xe2, 0x20, 0x6d, 0x94, 0x43, 0xa5, 0x01,
	0xde, 0xc0, 0xe9, 0x3b, 0x5b, 0x8b, 0x7a, 0x7b, 0xcc, 0x21, 0x74, 0xa7, 0xc7, 0x8b, 0x3c, 0x84,
	0x4a, 0xbc, 0xe4, 0xbc, 0x0a, 0xd0, 0x20, 0x6e, 0xa5, 0x5f, 0x6a, 0xfe, 0x1b, 0x00, 0x00, 0xff,
	0xff, 0x21, 0x6a, 0x43, 0xd4, 0xb3, 0x02, 0x00, 0x00,
}
