// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab-batch.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LabBatch struct {
	Id            string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location      *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Batch         string    `protobuf:"bytes,3,opt,name=batch,proto3" json:"batch,omitempty"`
	SupplierBatch string    `protobuf:"bytes,4,opt,name=supplierBatch,proto3" json:"supplierBatch,omitempty"`
	// double stock = 5;
	Date     *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	Expires  *timestamp.Timestamp `protobuf:"bytes,7,opt,name=expires,proto3" json:"expires,omitempty"`
	Supplier *Supplier            `protobuf:"bytes,9,opt,name=supplier,proto3" json:"supplier,omitempty"`
	// int32 health = 10;
	// int32 inflamability = 11;
	// int32 reactivity = 12;
	LabMaterial          *LabMaterial         `protobuf:"bytes,13,opt,name=labMaterial,proto3" json:"labMaterial,omitempty"`
	Manufactured         *timestamp.Timestamp `protobuf:"bytes,14,opt,name=manufactured,proto3" json:"manufactured,omitempty"`
	Reanalysis           *timestamp.Timestamp `protobuf:"bytes,15,opt,name=reanalysis,proto3" json:"reanalysis,omitempty"`
	Result               string               `protobuf:"bytes,16,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LabBatch) Reset()         { *m = LabBatch{} }
func (m *LabBatch) String() string { return proto.CompactTextString(m) }
func (*LabBatch) ProtoMessage()    {}
func (*LabBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_batch_ff457187944ad4ce, []int{0}
}
func (m *LabBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabBatch.Unmarshal(m, b)
}
func (m *LabBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabBatch.Marshal(b, m, deterministic)
}
func (dst *LabBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabBatch.Merge(dst, src)
}
func (m *LabBatch) XXX_Size() int {
	return xxx_messageInfo_LabBatch.Size(m)
}
func (m *LabBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_LabBatch.DiscardUnknown(m)
}

var xxx_messageInfo_LabBatch proto.InternalMessageInfo

func (m *LabBatch) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LabBatch) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LabBatch) GetBatch() string {
	if m != nil {
		return m.Batch
	}
	return ""
}

func (m *LabBatch) GetSupplierBatch() string {
	if m != nil {
		return m.SupplierBatch
	}
	return ""
}

func (m *LabBatch) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *LabBatch) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

func (m *LabBatch) GetSupplier() *Supplier {
	if m != nil {
		return m.Supplier
	}
	return nil
}

func (m *LabBatch) GetLabMaterial() *LabMaterial {
	if m != nil {
		return m.LabMaterial
	}
	return nil
}

func (m *LabBatch) GetManufactured() *timestamp.Timestamp {
	if m != nil {
		return m.Manufactured
	}
	return nil
}

func (m *LabBatch) GetReanalysis() *timestamp.Timestamp {
	if m != nil {
		return m.Reanalysis
	}
	return nil
}

func (m *LabBatch) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*LabBatch)(nil), "pb.LabBatch")
}

func init() { proto.RegisterFile("lab-batch.proto", fileDescriptor_lab_batch_ff457187944ad4ce) }

var fileDescriptor_lab_batch_ff457187944ad4ce = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x39, 0x4f, 0x03, 0x31,
	0x10, 0x85, 0x95, 0x4d, 0xc8, 0x31, 0xb9, 0xd0, 0x08, 0x21, 0x2b, 0x0d, 0x11, 0xa2, 0x48, 0x83,
	0x23, 0x8e, 0x8a, 0x82, 0x82, 0x3a, 0x34, 0x0b, 0x7f, 0x60, 0x9c, 0x75, 0x82, 0x25, 0x6f, 0x6c,
	0xd9, 0x5e, 0x04, 0xbf, 0x94, 0xbf, 0x83, 0xe2, 0xac, 0x73, 0x54, 0x29, 0xe7, 0xcd, 0xf7, 0xfc,
	0xfc, 0x06, 0xc6, 0x9a, 0xc4, 0xbd, 0xa0, 0xb0, 0xfc, 0xe2, 0xd6, 0x99, 0x60, 0x30, 0xb3, 0x62,
	0x72, 0xb3, 0x36, 0x66, 0xad, 0xe5, 0x3c, 0x2a, 0xa2, 0x5a, 0xcd, 0x83, 0x2a, 0xa5, 0x0f, 0x54,
	0xda, 0x1d, 0x34, 0xc1, 0xad, 0xab, 0xa4, 0x20, 0x9d, 0x22, 0x5d, 0x6b, 0x23, 0x6d, 0x96, 0x14,
	0x94, 0xd9, 0xa4, 0xd9, 0x57, 0xd6, 0x6a, 0x25, 0x5d, 0x9a, 0xc9, 0x5a, 0x67, 0xbe, 0x13, 0x7f,
	0xfb, 0xd7, 0x84, 0xee, 0x82, 0xc4, 0xdb, 0x36, 0x1b, 0x47, 0x90, 0xa9, 0x82, 0x35, 0xa6, 0x8d,
	0x59, 0x2f, 0xcf, 0x54, 0x81, 0x33, 0xe8, 0xa6, 0xe7, 0x58, 0x36, 0x6d, 0xcc, 0xfa, 0x8f, 0x03,
	0x6e, 0x05, 0x5f, 0xd4, 0x5a, 0xbe, 0xdf, 0xe2, 0x15, 0x5c, 0xc4, 0xef, 0xb3, 0x66, 0x34, 0xef,
	0x06, 0xbc, 0x83, 0x61, 0x8a, 0x8f, 0x01, 0xac, 0x15, 0xb7, 0xa7, 0x22, 0x72, 0x68, 0x15, 0x14,
	0x24, 0x6b, 0xc7, 0x84, 0x09, 0xdf, 0xd5, 0xe6, 0xa9, 0x36, 0xff, 0x4c, 0xb5, 0xf3, 0xc8, 0xe1,
	0x33, 0x74, 0xe4, 0x8f, 0x55, 0x4e, 0x7a, 0xd6, 0x39, 0x6b, 0x49, 0xe8, 0xb6, 0x4b, 0x8a, 0x65,
	0xbd, 0x43, 0x97, 0x8f, 0x5a, 0xcb, 0xf7, 0x5b, 0x7c, 0x80, 0xbe, 0x26, 0xf1, 0x5e, 0xdf, 0x95,
	0x0d, 0x23, 0x3c, 0x8e, 0xc5, 0x0f, 0x72, 0x7e, 0xcc, 0xe0, 0x2b, 0x0c, 0x4a, 0xda, 0x54, 0x2b,
	0x5a, 0x86, 0xca, 0xc9, 0x82, 0x8d, 0xce, 0xfe, 0xeb, 0x84, 0xc7, 0x17, 0x00, 0x27, 0x69, 0x43,
	0xfa, 0xd7, 0x2b, 0xcf, 0xc6, 0x67, 0xdd, 0x47, 0x34, 0x5e, 0x43, 0xdb, 0x49, 0x5f, 0xe9, 0xc0,
	0x2e, 0xe3, 0x75, 0xeb, 0x49, 0xb4, 0xa3, 0xef, 0xe9, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x8f,
	0x19, 0xd2, 0x5c, 0x02, 0x00, 0x00,
}
