// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab-batch-service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LabBatchList struct {
	Batches              []*LabBatch `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LabBatchList) Reset()         { *m = LabBatchList{} }
func (m *LabBatchList) String() string { return proto.CompactTextString(m) }
func (*LabBatchList) ProtoMessage()    {}
func (*LabBatchList) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_batch_service_ac975d7f221e57a6, []int{0}
}
func (m *LabBatchList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabBatchList.Unmarshal(m, b)
}
func (m *LabBatchList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabBatchList.Marshal(b, m, deterministic)
}
func (dst *LabBatchList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabBatchList.Merge(dst, src)
}
func (m *LabBatchList) XXX_Size() int {
	return xxx_messageInfo_LabBatchList.Size(m)
}
func (m *LabBatchList) XXX_DiscardUnknown() {
	xxx_messageInfo_LabBatchList.DiscardUnknown(m)
}

var xxx_messageInfo_LabBatchList proto.InternalMessageInfo

func (m *LabBatchList) GetBatches() []*LabBatch {
	if m != nil {
		return m.Batches
	}
	return nil
}

type GridBatchRequest struct {
	Grid                 *GridInput `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GridBatchRequest) Reset()         { *m = GridBatchRequest{} }
func (m *GridBatchRequest) String() string { return proto.CompactTextString(m) }
func (*GridBatchRequest) ProtoMessage()    {}
func (*GridBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_batch_service_ac975d7f221e57a6, []int{1}
}
func (m *GridBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridBatchRequest.Unmarshal(m, b)
}
func (m *GridBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridBatchRequest.Marshal(b, m, deterministic)
}
func (dst *GridBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridBatchRequest.Merge(dst, src)
}
func (m *GridBatchRequest) XXX_Size() int {
	return xxx_messageInfo_GridBatchRequest.Size(m)
}
func (m *GridBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GridBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GridBatchRequest proto.InternalMessageInfo

func (m *GridBatchRequest) GetGrid() *GridInput {
	if m != nil {
		return m.Grid
	}
	return nil
}

type GridBatch struct {
	Grid                 *GridOutput `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	Rows                 []*LabBatch `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GridBatch) Reset()         { *m = GridBatch{} }
func (m *GridBatch) String() string { return proto.CompactTextString(m) }
func (*GridBatch) ProtoMessage()    {}
func (*GridBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_batch_service_ac975d7f221e57a6, []int{2}
}
func (m *GridBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GridBatch.Unmarshal(m, b)
}
func (m *GridBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GridBatch.Marshal(b, m, deterministic)
}
func (dst *GridBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GridBatch.Merge(dst, src)
}
func (m *GridBatch) XXX_Size() int {
	return xxx_messageInfo_GridBatch.Size(m)
}
func (m *GridBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_GridBatch.DiscardUnknown(m)
}

var xxx_messageInfo_GridBatch proto.InternalMessageInfo

func (m *GridBatch) GetGrid() *GridOutput {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *GridBatch) GetRows() []*LabBatch {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*LabBatchList)(nil), "pb.LabBatchList")
	proto.RegisterType((*GridBatchRequest)(nil), "pb.GridBatchRequest")
	proto.RegisterType((*GridBatch)(nil), "pb.GridBatch")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LabBatchServiceClient is the client API for LabBatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LabBatchServiceClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Load(ctx context.Context, in *Request, opts ...grpc.CallOption) (*LabBatch, error)
	Create(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*LabBatchList, error)
	Validate(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*Response, error)
	GenBatchCode(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*LabBatch, error)
	Grid(ctx context.Context, in *GridBatchRequest, opts ...grpc.CallOption) (*GridBatch, error)
}

type labBatchServiceClient struct {
	cc *grpc.ClientConn
}

func NewLabBatchServiceClient(cc *grpc.ClientConn) LabBatchServiceClient {
	return &labBatchServiceClient{cc}
}

func (c *labBatchServiceClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labBatchServiceClient) Load(ctx context.Context, in *Request, opts ...grpc.CallOption) (*LabBatch, error) {
	out := new(LabBatch)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labBatchServiceClient) Create(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labBatchServiceClient) Update(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labBatchServiceClient) List(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*LabBatchList, error) {
	out := new(LabBatchList)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labBatchServiceClient) Validate(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labBatchServiceClient) GenBatchCode(ctx context.Context, in *LabBatch, opts ...grpc.CallOption) (*LabBatch, error) {
	out := new(LabBatch)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/GenBatchCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labBatchServiceClient) Grid(ctx context.Context, in *GridBatchRequest, opts ...grpc.CallOption) (*GridBatch, error) {
	out := new(GridBatch)
	err := c.cc.Invoke(ctx, "/pb.LabBatchService/Grid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabBatchServiceServer is the server API for LabBatchService service.
type LabBatchServiceServer interface {
	Ping(context.Context, *Request) (*Response, error)
	Load(context.Context, *Request) (*LabBatch, error)
	Create(context.Context, *LabBatch) (*Response, error)
	Update(context.Context, *LabBatch) (*Response, error)
	List(context.Context, *LabBatch) (*LabBatchList, error)
	Validate(context.Context, *LabBatch) (*Response, error)
	GenBatchCode(context.Context, *LabBatch) (*LabBatch, error)
	Grid(context.Context, *GridBatchRequest) (*GridBatch, error)
}

func RegisterLabBatchServiceServer(s *grpc.Server, srv LabBatchServiceServer) {
	s.RegisterService(&_LabBatchService_serviceDesc, srv)
}

func _LabBatchService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabBatchService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).Load(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabBatchService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).Create(ctx, req.(*LabBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabBatchService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).Update(ctx, req.(*LabBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabBatchService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).List(ctx, req.(*LabBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabBatchService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).Validate(ctx, req.(*LabBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabBatchService_GenBatchCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).GenBatchCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/GenBatchCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).GenBatchCode(ctx, req.(*LabBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LabBatchService_Grid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabBatchServiceServer).Grid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.LabBatchService/Grid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabBatchServiceServer).Grid(ctx, req.(*GridBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LabBatchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LabBatchService",
	HandlerType: (*LabBatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LabBatchService_Ping_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _LabBatchService_Load_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _LabBatchService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _LabBatchService_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _LabBatchService_List_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _LabBatchService_Validate_Handler,
		},
		{
			MethodName: "GenBatchCode",
			Handler:    _LabBatchService_GenBatchCode_Handler,
		},
		{
			MethodName: "Grid",
			Handler:    _LabBatchService_Grid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lab-batch-service.proto",
}

func init() {
	proto.RegisterFile("lab-batch-service.proto", fileDescriptor_lab_batch_service_ac975d7f221e57a6)
}

var fileDescriptor_lab_batch_service_ac975d7f221e57a6 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x5f, 0x4b, 0xf3, 0x30,
	0x18, 0xc5, 0xb7, 0xbd, 0x65, 0xaf, 0x3e, 0xeb, 0xfe, 0x10, 0x04, 0x47, 0xaf, 0x66, 0x84, 0xb1,
	0x0b, 0xb7, 0x8b, 0x89, 0x7e, 0x00, 0x77, 0x31, 0x84, 0x82, 0x3a, 0xd1, 0xfb, 0x64, 0x0d, 0x33,
	0x30, 0x9a, 0x98, 0xa4, 0xfa, 0x65, 0xfd, 0x30, 0x92, 0xa4, 0x29, 0x2d, 0x16, 0xf4, 0xae, 0xcf,
	0x73, 0x7e, 0xe7, 0x34, 0x3d, 0x0d, 0x9c, 0x1f, 0x09, 0x5d, 0x52, 0x62, 0xf6, 0x6f, 0x4b, 0xcd,
	0xd4, 0x07, 0xdf, 0xb3, 0x95, 0x54, 0xc2, 0x08, 0xd4, 0x93, 0x34, 0x19, 0x57, 0xa2, 0x5f, 0x26,
	0x43, 0xc5, 0xde, 0x0b, 0xa6, 0x4d, 0x39, 0x8e, 0x14, 0xd3, 0x52, 0xe4, 0xba, 0xf4, 0x24, 0x70,
	0x50, 0x3c, 0xf3, 0xcf, 0xf8, 0x16, 0xe2, 0x94, 0xd0, 0x3b, 0x6b, 0x4e, 0xb9, 0x36, 0x68, 0x0e,
	0xff, 0x5d, 0x12, 0xd3, 0xd3, 0xee, 0xec, 0xdf, 0x62, 0xb0, 0x8e, 0x57, 0x92, 0xae, 0x02, 0xb2,
	0x0b, 0x22, 0xbe, 0x81, 0xc9, 0x56, 0xf1, 0xcc, 0x6f, 0xfd, 0xdb, 0xd0, 0x05, 0x44, 0x36, 0x79,
	0xda, 0x9d, 0x75, 0x17, 0x83, 0xf5, 0xd0, 0x1a, 0x2d, 0x73, 0x9f, 0xcb, 0xc2, 0xec, 0x9c, 0x84,
	0x9f, 0xe0, 0xb4, 0xb2, 0x21, 0xdc, 0xe0, 0x47, 0x81, 0x7f, 0x28, 0x4c, 0x65, 0x40, 0x33, 0x88,
	0x94, 0xf8, 0xd4, 0xd3, 0x5e, 0xcb, 0x61, 0x9c, 0xb2, 0xfe, 0xea, 0xc1, 0x38, 0xac, 0x9e, 0x7d,
	0x37, 0xe8, 0x12, 0xa2, 0x47, 0x9e, 0x1f, 0xd0, 0xc0, 0xf2, 0xe5, 0xf1, 0x92, 0xd8, 0x0f, 0xbe,
	0x0a, 0xdc, 0xb1, 0x50, 0x2a, 0x48, 0xd6, 0x02, 0x85, 0x38, 0xdc, 0x41, 0x73, 0xe8, 0x6f, 0x14,
	0x23, 0x86, 0xa1, 0x86, 0xf2, 0x23, 0x6c, 0x0e, 0xfd, 0x17, 0x99, 0xfd, 0xce, 0x2d, 0x20, 0x72,
	0x3d, 0x37, 0xa9, 0x49, 0x7d, 0xb2, 0xba, 0x23, 0x4f, 0x5e, 0xc9, 0x91, 0xff, 0x21, 0xf3, 0x0a,
	0xe2, 0x2d, 0xcb, 0x9d, 0xb6, 0x11, 0x59, 0x2b, 0x5d, 0xfb, 0xa2, 0x25, 0x44, 0xb6, 0x65, 0x74,
	0x16, 0xfa, 0xae, 0xff, 0xc3, 0x64, 0xd8, 0xd8, 0xe2, 0x0e, 0xed, 0xbb, 0x7b, 0x72, 0xfd, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x56, 0x1b, 0xad, 0x5e, 0x82, 0x02, 0x00, 0x00,
}
