// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lab-settings.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LabSettings struct {
	BaseDomain   string `protobuf:"bytes,1,opt,name=baseDomain,proto3" json:"baseDomain,omitempty"`
	DaysToExpire int32  `protobuf:"varint,2,opt,name=daysToExpire,proto3" json:"daysToExpire,omitempty"`
	// string mailKey = 3;
	NotifyAreas          []string `protobuf:"bytes,4,rep,name=notifyAreas,proto3" json:"notifyAreas,omitempty"`
	SenderAddress        string   `protobuf:"bytes,5,opt,name=senderAddress,proto3" json:"senderAddress,omitempty"`
	GroupLaboratory      string   `protobuf:"bytes,7,opt,name=groupLaboratory,proto3" json:"groupLaboratory,omitempty"`
	GroupPurchasing      string   `protobuf:"bytes,8,opt,name=groupPurchasing,proto3" json:"groupPurchasing,omitempty"`
	GroupQA              string   `protobuf:"bytes,9,opt,name=groupQA,proto3" json:"groupQA,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabSettings) Reset()         { *m = LabSettings{} }
func (m *LabSettings) String() string { return proto.CompactTextString(m) }
func (*LabSettings) ProtoMessage()    {}
func (*LabSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_lab_settings_9fd5167e10e391d0, []int{0}
}
func (m *LabSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabSettings.Unmarshal(m, b)
}
func (m *LabSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabSettings.Marshal(b, m, deterministic)
}
func (dst *LabSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabSettings.Merge(dst, src)
}
func (m *LabSettings) XXX_Size() int {
	return xxx_messageInfo_LabSettings.Size(m)
}
func (m *LabSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_LabSettings.DiscardUnknown(m)
}

var xxx_messageInfo_LabSettings proto.InternalMessageInfo

func (m *LabSettings) GetBaseDomain() string {
	if m != nil {
		return m.BaseDomain
	}
	return ""
}

func (m *LabSettings) GetDaysToExpire() int32 {
	if m != nil {
		return m.DaysToExpire
	}
	return 0
}

func (m *LabSettings) GetNotifyAreas() []string {
	if m != nil {
		return m.NotifyAreas
	}
	return nil
}

func (m *LabSettings) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

func (m *LabSettings) GetGroupLaboratory() string {
	if m != nil {
		return m.GroupLaboratory
	}
	return ""
}

func (m *LabSettings) GetGroupPurchasing() string {
	if m != nil {
		return m.GroupPurchasing
	}
	return ""
}

func (m *LabSettings) GetGroupQA() string {
	if m != nil {
		return m.GroupQA
	}
	return ""
}

func init() {
	proto.RegisterType((*LabSettings)(nil), "pb.LabSettings")
}

func init() { proto.RegisterFile("lab-settings.proto", fileDescriptor_lab_settings_9fd5167e10e391d0) }

var fileDescriptor_lab_settings_9fd5167e10e391d0 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0xcd, 0x4a, 0xc4, 0x40,
	0x0c, 0xc0, 0x71, 0x5a, 0x5d, 0xd7, 0x66, 0x15, 0x21, 0xa7, 0x9c, 0xa4, 0x2c, 0x1e, 0x7a, 0xd1,
	0x8b, 0x4f, 0x50, 0xd0, 0xdb, 0x1e, 0xb4, 0xfa, 0x02, 0x19, 0x3b, 0xd6, 0x01, 0x9d, 0x94, 0x64,
	0x16, 0xec, 0x13, 0xf8, 0xda, 0xc2, 0xe0, 0x47, 0xbb, 0xc7, 0xfc, 0xf2, 0x87, 0x40, 0x00, 0xdf,
	0xd9, 0x5d, 0x9b, 0x4f, 0x29, 0xc4, 0xc1, 0x6e, 0x46, 0x95, 0x24, 0x58, 0x8e, 0x6e, 0xfb, 0x55,
	0xc2, 0x66, 0xc7, 0xee, 0xe9, 0x67, 0x83, 0x97, 0x00, 0x8e, 0xcd, 0xdf, 0xc9, 0x07, 0x87, 0x48,
	0x45, 0x5d, 0x34, 0x55, 0x37, 0x13, 0xdc, 0xc2, 0x59, 0xcf, 0x93, 0x3d, 0xcb, 0xfd, 0xe7, 0x18,
	0xd4, 0x53, 0x59, 0x17, 0xcd, 0xaa, 0x5b, 0x18, 0xd6, 0xb0, 0x89, 0x92, 0xc2, 0xeb, 0xd4, 0xaa,
	0x67, 0xa3, 0xe3, 0xfa, 0xa8, 0xa9, 0xba, 0x39, 0xe1, 0x15, 0x9c, 0x9b, 0x8f, 0xbd, 0xd7, 0xb6,
	0xef, 0xd5, 0x9b, 0xd1, 0x2a, 0x1f, 0x5a, 0x22, 0x36, 0x70, 0x31, 0xa8, 0xec, 0xc7, 0x1d, 0x3b,
	0x51, 0x4e, 0xa2, 0x13, 0xad, 0x73, 0x77, 0xc8, 0x7f, 0xe5, 0xc3, 0x5e, 0x5f, 0xde, 0xd8, 0x42,
	0x1c, 0xe8, 0x74, 0x56, 0xfe, 0x33, 0x12, 0xac, 0x33, 0x3d, 0xb6, 0x54, 0xe5, 0xe2, 0x77, 0x74,
	0x27, 0xf9, 0x29, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x88, 0xfd, 0x43, 0x2a, 0x01,
	0x00, 0x00,
}
