// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *User                `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
	IpAddress            string               `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_session_1b7680b18c4bf308, []int{0}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Session) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Session) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

func (m *Session) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Session)(nil), "pb.Session")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor_session_1b7680b18c4bf308) }

var fileDescriptor_session_1b7680b18c4bf308 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0x41, 0x4a, 0xc4, 0x30,
	0x14, 0x86, 0x49, 0xac, 0xd6, 0x3e, 0xd1, 0x45, 0x56, 0xa1, 0x14, 0x2c, 0xae, 0xba, 0x4a, 0x41,
	0x5d, 0xb9, 0xf3, 0x0a, 0x55, 0x0f, 0xd0, 0x98, 0x37, 0x25, 0x30, 0x6d, 0x42, 0x5e, 0x0a, 0x73,
	0xc3, 0xb9, 0xd6, 0x30, 0x09, 0x65, 0x66, 0x37, 0xbb, 0xf0, 0xf1, 0xfd, 0xf9, 0x1e, 0x3c, 0x13,
	0x12, 0x59, 0xb7, 0x28, 0x1f, 0x5c, 0x74, 0x82, 0x7b, 0x5d, 0xbf, 0x4e, 0xce, 0x4d, 0x7b, 0xec,
	0x13, 0xd1, 0xeb, 0xae, 0x8f, 0x76, 0x46, 0x8a, 0xe3, 0xec, 0xb3, 0x54, 0xc3, 0x4a, 0x18, 0xf2,
	0xfb, 0xed, 0xc8, 0xa0, 0xfc, 0xc9, 0x5f, 0x88, 0x17, 0xe0, 0xd6, 0x48, 0xd6, 0xb2, 0xae, 0x1a,
	0xb8, 0x35, 0xa2, 0x81, 0xe2, 0x6c, 0x4a, 0xde, 0xb2, 0xee, 0xe9, 0xfd, 0x51, 0x79, 0xad, 0xfe,
	0x08, 0xc3, 0x90, 0xa8, 0xf8, 0x84, 0xf2, 0x3f, 0xe0, 0x18, 0xd1, 0xc8, 0xbb, 0x24, 0xd4, 0x2a,
	0x87, 0xd5, 0x16, 0x56, 0xbf, 0x5b, 0x78, 0xd8, 0x54, 0xf1, 0x05, 0x80, 0x07, 0x6f, 0xc3, 0x18,
	0xad, 0x5b, 0x64, 0x71, 0x73, 0x78, 0x65, 0x8b, 0x06, 0x2a, 0xeb, 0xbf, 0x8d, 0x09, 0x48, 0x24,
	0xef, 0xd3, 0x99, 0x17, 0xa0, 0x1f, 0xd2, 0xfa, 0xe3, 0x14, 0x00, 0x00, 0xff, 0xff, 0x03, 0x6e,
	0x82, 0x6b, 0x12, 0x01, 0x00, 0x00,
}
