// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supplier-service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SupplierListResponse struct {
	Suppliers            []*Supplier `protobuf:"bytes,1,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SupplierListResponse) Reset()         { *m = SupplierListResponse{} }
func (m *SupplierListResponse) String() string { return proto.CompactTextString(m) }
func (*SupplierListResponse) ProtoMessage()    {}
func (*SupplierListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_supplier_service_3055cd369d59ce1e, []int{0}
}
func (m *SupplierListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupplierListResponse.Unmarshal(m, b)
}
func (m *SupplierListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupplierListResponse.Marshal(b, m, deterministic)
}
func (dst *SupplierListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupplierListResponse.Merge(dst, src)
}
func (m *SupplierListResponse) XXX_Size() int {
	return xxx_messageInfo_SupplierListResponse.Size(m)
}
func (m *SupplierListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SupplierListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SupplierListResponse proto.InternalMessageInfo

func (m *SupplierListResponse) GetSuppliers() []*Supplier {
	if m != nil {
		return m.Suppliers
	}
	return nil
}

func init() {
	proto.RegisterType((*SupplierListResponse)(nil), "pb.SupplierListResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SupplierServiceClient is the client API for SupplierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SupplierServiceClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Load(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Supplier, error)
	Create(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error)
	Validate(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*SupplierListResponse, error)
}

type supplierServiceClient struct {
	cc *grpc.ClientConn
}

func NewSupplierServiceClient(cc *grpc.ClientConn) SupplierServiceClient {
	return &supplierServiceClient{cc}
}

func (c *supplierServiceClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) Load(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Supplier, error) {
	out := new(Supplier)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) Create(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) Update(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) Remove(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) Validate(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) List(ctx context.Context, in *Supplier, opts ...grpc.CallOption) (*SupplierListResponse, error) {
	out := new(SupplierListResponse)
	err := c.cc.Invoke(ctx, "/pb.SupplierService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupplierServiceServer is the server API for SupplierService service.
type SupplierServiceServer interface {
	Ping(context.Context, *Request) (*Response, error)
	Load(context.Context, *Supplier) (*Supplier, error)
	Create(context.Context, *Supplier) (*Response, error)
	Update(context.Context, *Supplier) (*Response, error)
	Remove(context.Context, *Supplier) (*Response, error)
	Validate(context.Context, *Supplier) (*Response, error)
	List(context.Context, *Supplier) (*SupplierListResponse, error)
}

func RegisterSupplierServiceServer(s *grpc.Server, srv SupplierServiceServer) {
	s.RegisterService(&_SupplierService_serviceDesc, srv)
}

func _SupplierService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supplier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).Load(ctx, req.(*Supplier))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supplier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).Create(ctx, req.(*Supplier))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supplier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).Update(ctx, req.(*Supplier))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supplier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).Remove(ctx, req.(*Supplier))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supplier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).Validate(ctx, req.(*Supplier))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Supplier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SupplierService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).List(ctx, req.(*Supplier))
	}
	return interceptor(ctx, in, info, handler)
}

var _SupplierService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SupplierService",
	HandlerType: (*SupplierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SupplierService_Ping_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _SupplierService_Load_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SupplierService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SupplierService_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _SupplierService_Remove_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _SupplierService_Validate_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SupplierService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supplier-service.proto",
}

func init() {
	proto.RegisterFile("supplier-service.proto", fileDescriptor_supplier_service_3055cd369d59ce1e)
}

var fileDescriptor_supplier_service_3055cd369d59ce1e = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2e, 0x2d, 0x28,
	0xc8, 0xc9, 0x4c, 0x2d, 0xd2, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x86,
	0x8a, 0x49, 0xf1, 0x16, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x40, 0xb9, 0x7c, 0x30, 0xad, 0x10,
	0xbe, 0x92, 0x13, 0x97, 0x48, 0x30, 0x54, 0xc4, 0x27, 0xb3, 0xb8, 0x24, 0x08, 0xaa, 0x59, 0x48,
	0x8b, 0x8b, 0x13, 0xa6, 0xb2, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88, 0x47, 0xaf, 0x20,
	0x49, 0x0f, 0xa6, 0x38, 0x08, 0x21, 0x6d, 0xb4, 0x81, 0x89, 0x8b, 0x1f, 0x26, 0x1e, 0x0c, 0x71,
	0x90, 0x90, 0x32, 0x17, 0x4b, 0x40, 0x66, 0x5e, 0xba, 0x10, 0x37, 0x48, 0x53, 0x10, 0xc4, 0x09,
	0x52, 0x3c, 0x10, 0x0e, 0xc4, 0x0a, 0x25, 0x06, 0x21, 0x15, 0x2e, 0x16, 0x9f, 0xfc, 0xc4, 0x14,
	0x21, 0x14, 0x93, 0xa5, 0x50, 0x78, 0x4a, 0x0c, 0x42, 0x6a, 0x5c, 0x6c, 0xce, 0x45, 0xa9, 0x89,
	0x25, 0xa9, 0xd8, 0xd4, 0x21, 0x99, 0xa6, 0xc6, 0xc5, 0x16, 0x5a, 0x90, 0x42, 0x94, 0xba, 0xa0,
	0xd4, 0xdc, 0xfc, 0x32, 0x42, 0xea, 0x34, 0xb8, 0x38, 0xc2, 0x12, 0x73, 0x32, 0x89, 0x30, 0xd1,
	0x80, 0x8b, 0x05, 0x14, 0x78, 0x68, 0xaa, 0x24, 0x90, 0x79, 0xc8, 0x81, 0xab, 0xc4, 0x90, 0xc4,
	0x06, 0x0e, 0x7d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x92, 0xec, 0xb9, 0xca, 0x01,
	0x00, 0x00,
}
