// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user-settings.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserSettings struct {
	NotifyAllMaterials   bool     `protobuf:"varint,1,opt,name=notifyAllMaterials,proto3" json:"notifyAllMaterials,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSettings) Reset()         { *m = UserSettings{} }
func (m *UserSettings) String() string { return proto.CompactTextString(m) }
func (*UserSettings) ProtoMessage()    {}
func (*UserSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_settings_c3c1f4b4a093ee50, []int{0}
}
func (m *UserSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSettings.Unmarshal(m, b)
}
func (m *UserSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSettings.Marshal(b, m, deterministic)
}
func (dst *UserSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSettings.Merge(dst, src)
}
func (m *UserSettings) XXX_Size() int {
	return xxx_messageInfo_UserSettings.Size(m)
}
func (m *UserSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSettings.DiscardUnknown(m)
}

var xxx_messageInfo_UserSettings proto.InternalMessageInfo

func (m *UserSettings) GetNotifyAllMaterials() bool {
	if m != nil {
		return m.NotifyAllMaterials
	}
	return false
}

func (m *UserSettings) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UserSettings)(nil), "pb.UserSettings")
}

func init() { proto.RegisterFile("user-settings.proto", fileDescriptor_user_settings_c3c1f4b4a093ee50) }

var fileDescriptor_user_settings_c3c1f4b4a093ee50 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2d, 0x4e, 0x2d, 0x29, 0xc9, 0xcc, 0x4b, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x2a, 0x48, 0x92, 0xe2, 0x02, 0x49, 0x40, 0xf8, 0x4a, 0x31, 0x5c, 0x3c, 0xa1, 0xc5, 0xa9,
	0x45, 0xc1, 0x50, 0x55, 0x42, 0x7a, 0x5c, 0x42, 0x79, 0xf9, 0x25, 0x99, 0x69, 0x95, 0x8e, 0x39,
	0x39, 0xbe, 0x89, 0x25, 0xa9, 0x45, 0x99, 0x89, 0x39, 0xc5, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x1c,
	0x41, 0x58, 0x64, 0x84, 0x64, 0xb8, 0x58, 0x40, 0xa6, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b,
	0x71, 0xe8, 0x15, 0x24, 0xe9, 0x81, 0xcc, 0x0b, 0x02, 0x8b, 0x26, 0xb1, 0x81, 0x2d, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x96, 0xf8, 0x08, 0xe0, 0x8b, 0x00, 0x00, 0x00,
}
